import array as arr
b=[1,2,3]
b.append("abc")
print("list",b)
a=arr.array('i',[22,3,3,4,8,1,1])
a.append(6)
print("list: ",a)
print("count: ",a.count(1))
print("arr.buffer_info: ",a.buffer_info())
print("arr.revers: e",a[::-1])
print(a)
a.reverse()
print("a",a)
a.append(12)
a.insert(2,21)
print("a",a)
a.insert(2,12)
print("a",a)
print("pop ",a.pop())
print("a after pop without index",a)
print("pop ",a.pop(1))
print("a after pop with index",a)
print("index ",a.index(1))
print(a.remove(1))
print(a)